In [2]:
import tensorflow as tf
import numpy as np
import keras

2024-04-16 12:49:44.651425: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
PLAIN_TYPES = (str, int, float, bool)
def serialize_keras_object(obj):
    if isinstance(obj,PLAIN_TYPES):
        print("haha")
    else:
        print("heihei")
serialize_keras_object(1)

haha


In [3]:
def get_config():
    config1 = {
        "1":1,
        "2":2
    }
    config2 = {
        "3":3,
        "4":4
    }
    return {**config1,**config2}
get_config()

{'1': 1, '2': 2, '3': 3, '4': 4}

In [12]:
x = tf.convert_to_tensor([1,2,3,4])
keras.tree.is_nested(x)

False

In [17]:
list1 = (1,2,3)
list2 = (2,3,4)
tuple(list1) + tuple(list2)
(list1,) + list2

((1, 2, 3), 2, 3, 4)

In [18]:
list1 + list2

(1, 2, 3, 2, 3, 4)

In [19]:
len(list1)


3

In [27]:
class ThisIsATest:
    def __init__(self) -> None:
        pass
obj = ThisIsATest()
obj.__class__.__name__

'ThisIsATest'

In [34]:
import keras
from keras.losses import Loss

from keras.losses import BinaryCrossentropy
from keras.losses import BinaryFocalCrossentropy
from keras.losses import CategoricalCrossentropy
from keras.losses import CategoricalFocalCrossentropy
from keras.losses import CategoricalHinge
from keras.losses import CosineSimilarity
#from keras.losses import Dice
from keras.losses import Hinge
from keras.losses import Huber
from keras.losses import KLDivergence
from keras.losses import LogCosh
#from keras.losses import LossFunctionWrapper
from keras.losses import MeanAbsoluteError
from keras.losses import MeanAbsolutePercentageError
from keras.losses import MeanSquaredError
from keras.losses import MeanSquaredLogarithmicError
from keras.losses import Poisson
from keras.losses import SparseCategoricalCrossentropy
from keras.losses import SquaredHinge

from keras.losses import binary_crossentropy
from keras.losses import binary_focal_crossentropy
from keras.losses import categorical_crossentropy
from keras.losses import categorical_focal_crossentropy
from keras.losses import categorical_hinge
from keras.losses import cosine_similarity
from keras.losses import ctc
#from keras.losses import dice

from keras.losses import hinge
from keras.losses import huber
from keras.losses import kl_divergence
from keras.losses import log_cosh
from keras.losses import mean_absolute_error
from keras.losses import mean_absolute_percentage_error
from keras.losses import mean_squared_error
from keras.losses import mean_squared_logarithmic_error
from keras.losses import poisson
from keras.losses import sparse_categorical_crossentropy
from keras.losses import squared_hinge

ALL_OBJECTS = {
    # Base
    Loss,
    #LossFunctionWrapper,
    # Probabilistic
    KLDivergence,
    Poisson,
    BinaryCrossentropy,
    BinaryFocalCrossentropy,
    CategoricalCrossentropy,
    CategoricalFocalCrossentropy,
    SparseCategoricalCrossentropy,
    # Regression
    MeanSquaredError,
    MeanAbsoluteError,
    MeanAbsolutePercentageError,
    MeanSquaredLogarithmicError,
    CosineSimilarity,
    LogCosh,
    Huber,
    # Hinge
    Hinge,
    SquaredHinge,
    CategoricalHinge,
    # Image segmentation
    #Dice,
    # Probabilistic
    kl_divergence,
    poisson,
    binary_crossentropy,
    binary_focal_crossentropy,
    categorical_crossentropy,
    categorical_focal_crossentropy,
    sparse_categorical_crossentropy,
    # Regression
    mean_squared_error,
    mean_absolute_error,
    mean_absolute_percentage_error,
    mean_squared_logarithmic_error,
    cosine_similarity,
    log_cosh,
    huber,
    # Hinge
    hinge,
    squared_hinge,
    categorical_hinge,
    # Image segmentation
    #dice,
}

ALL_OBJECTS_DICT = {cls.__name__: cls for cls in ALL_OBJECTS}
ALL_OBJECTS_DICT.update(
    {
        "bce": binary_crossentropy,
        "BCE": binary_crossentropy,
        "kld": kl_divergence,
        "KLD": kl_divergence,
        "mae": mean_absolute_error,
        "MAE": mean_absolute_error,
        "mse": mean_squared_error,
        "MSE": mean_squared_error,
        "mape": mean_absolute_percentage_error,
        "MAPE": mean_absolute_percentage_error,
        "msle": mean_squared_logarithmic_error,
        "MSLE": mean_squared_logarithmic_error,
    }
)

In [37]:
for key, value in ALL_OBJECTS_DICT.items():
    print(key, value)

BinaryFocalCrossentropy <class 'keras.src.losses.losses.BinaryFocalCrossentropy'>
squared_hinge <function squared_hinge at 0x128804860>
sparse_categorical_crossentropy <function sparse_categorical_crossentropy at 0x128805080>
KLDivergence <class 'keras.src.losses.losses.KLDivergence'>
categorical_hinge <function categorical_hinge at 0x128804900>
binary_crossentropy <function binary_crossentropy at 0x128805120>
mean_squared_error <function mean_squared_error at 0x1288049a0>
CosineSimilarity <class 'keras.src.losses.losses.CosineSimilarity'>
binary_focal_crossentropy <function binary_focal_crossentropy at 0x1288051c0>
MeanAbsolutePercentageError <class 'keras.src.losses.losses.MeanAbsolutePercentageError'>
mean_absolute_error <function mean_absolute_error at 0x128804a40>
MeanSquaredError <class 'keras.src.losses.losses.MeanSquaredError'>
Loss <class 'keras.src.losses.loss.Loss'>
LogCosh <class 'keras.src.losses.losses.LogCosh'>
mean_absolute_percentage_error <function mean_absolute_perce

In [39]:
x = np.random.random((2,3,1))
tf.squeeze(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.35296089, 0.24586719, 0.76301279],
       [0.95401386, 0.04427627, 0.29244899]])>

In [8]:
num_classes = 6
x = [[1,2,0,-1,5],[0,3,2,2,4]]
x = np.array(x)
x = x.reshape(-1)
batch_size = x.shape[0]
categorical = np.zeros((batch_size, num_classes), dtype="float32")
valid_indices = x >= 0
valid_indices

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [9]:
index1 = np.arange(batch_size)[valid_indices]
index1

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [7]:
x[valid_indices]

array([1, 2, 0, 4, 5, 0, 3, 2, 2, 4])

In [10]:
categorical[np.arange(batch_size)[valid_indices], x[valid_indices]] = 1

In [11]:
categorical

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)