In [3]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.reshape(tf.range(12),(3,4))
y = tf.unstack(x)
y

[<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8,  9, 10, 11], dtype=int32)>]

##

## tf.tile(input, multiples, name)
```
Args:
    input: A `Tensor`. Can be of any rank.
    multiples: A `Tensor`. Must be one of the following types: `int32`, `int64`.
      1-D. Length must be the same as the number of dimensions in `input`
    name: A name for the operation (optional).

Returns:
    A `Tensor`. Has the same type as `input`.
```


In [4]:
a = tf.constant([[1,2,3],[4,5,6]], tf.int32)
b = tf.constant([1,2], tf.int32)
tf.tile(a, b)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]], dtype=int32)>

## tf.where


In [6]:
tf.where([True, False, False, True])

<tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[0],
       [3]])>

## tf.TensorArray


In [11]:
ta = tf.TensorArray(tf.float32, size=2, dynamic_size=True)
ta.unstack([0., 1., 3.])

In [12]:
ta.stack()

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 3.], dtype=float32)>

## tf.while_loop
Repeat body while the condition cond is true. (deprecated argument values)
```
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))

tf.while_loop(
    cond,
    body,
    loop_vars,
    shape_invariants=None,
    parallel_iterations=10,
    back_prop=True,
    swap_memory=False,
    maximum_iterations=None,
    name=None
)
Returns:
    The output tensors for the loop variables after the loop. The return value
      has the same structure as `loop_vars`.

```

## tf.keras.ops.while_loop
```
tf.keras.ops.while_loop(
    cond, body, loop_vars, maximum_iterations=None
)
Args:
    cond: A callable that represents the termination condition of the loop.
        Must accept a `loop_vars` like structure as an argument. If
        `loop_vars` is a tuple or list, each element of `loop_vars` will be
        passed positionally to the callable.
    body: A callable that represents the loop body. Must accept a
        `loop_vars` like structure as an argument, and return update value
        with the same structure. If `loop_vars` is a tuple or list, each
        element of `loop_vars` will be passed positionally to the callable.
    loop_vars: An arbitrary nested structure of tensor state to persist
        across loop iterations.
    maximum_iterations: Optional maximum number of iterations of the while
        loop to run. If provided, the `cond` output is AND-ed with an
        additional condition ensuring the number of iterations executed is
        no greater than `maximum_iterations`.

Returns:
    A list/tuple of tensors, has the same shape and dtype as `inputs`.
```


In [16]:
i = 0
cond = lambda i: i < 10
body = lambda i: i + 1
tf.keras.ops.while_loop(cond, body, i)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [17]:
x, y = 0, 1
cond = lambda x, y: x < 10
body = lambda x, y: (x + 1, y + 1)
tf.keras.ops.while_loop(cond, body, (x, y))


(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=11>)