In [1]:
import re
def to_snake_case(name):
    name = re.sub(r"\W+", "", name)
    name = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    name = re.sub("([a-z])([A-Z])", r"\1_\2", name).lower()
    return name

In [2]:
import tensorflow as tf

2024-04-19 08:59:43.990785: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
to_snake_case("BinaryIoU")

'binary_io_u'

In [7]:
mean = tf.keras.metrics.Mean()
mean.update_state([[1,2,3],[2,3,4]])
mean.result()

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [8]:
sum = tf.keras.metrics.Sum()
sum.update_state([[1,2,3],[2,3,4]])
sum.result()

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

In [9]:
import numpy as np
y_true = np.random.randint(0, 2, size=(2, 3))
y_pred = np.random.random(size=(2, 3))
loss = tf.keras.losses.mean_squared_error(y_true, y_pred)
loss

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.26689645, 0.31909442])>